using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Redeclare;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace Notify;

/// <summary>
///     Generates a change-notifying property for every field marked <c>[Notify]</c>, and gives the containing class
///     <c>INotifyPropertyChanged</c>, the event and the raise method when it has none of its own.
/// </summary>
/// <remarks>
///     The shape of the sample. The field and its class are read once, into the library's own declarations. The
///     class comes back as the shape of a new partial part, containing types included, so nesting costs nothing to
///     get right. The three facts the generator acts on are booleans answered by symbols and carried as values.
///     Property bodies name <c>EqualityComparer&lt;T&gt;</c> and <c>PropertyChangedEventArgs</c> through holes. A
///     class that is not partial all the way out is skipped, since complaining about it is an analyzer's job.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class NotifyGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     The name the step that reads the marked fields is tracked under, for the tests that assert what reruns
    ///     after an edit.
    /// </summary>
    public const string FieldsStep = "Fields";

    private const string AttributeMetadataName = "Notify.NotifyAttribute";

    private const string InterfaceMetadataName = "System.ComponentModel.INotifyPropertyChanged";

    private const string FileHeader = """
        // <auto-generated/>

        #nullable enable
        """;

    private const string Attribute = """
        // <auto-generated/>
        #nullable enable

        namespace Notify;

        /// <summary>
        ///     Marks a field that gets a generated change-notifying property.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Field)]
        internal sealed class NotifyAttribute : global::System.Attribute
        {
            /// <summary>
            ///     Gets or sets the property's name, the field's name without its leading underscore and capitalized when unset.
            /// </summary>
            public string? PropertyName { get; set; }
        }
        """;

    // The framework types the generated members mention. Naming them here keeps the render stage free of symbols.
    private static readonly NamedTypeReference _notifyPropertyChanged =
        new(Name: "INotifyPropertyChanged", ContainingNamespace: "System.ComponentModel", TypeKind: TypeKind.Interface);

    private static readonly NamedTypeReference _eventHandler =
        new(Name: "PropertyChangedEventHandler", ContainingNamespace: "System.ComponentModel", TypeKind: TypeKind.Delegate);

    private static readonly NamedTypeReference _eventArgs =
        new(Name: "PropertyChangedEventArgs", ContainingNamespace: "System.ComponentModel");

    private static readonly NamedTypeReference _equalityComparer =
        new(Name: "EqualityComparer", ContainingNamespace: "System.Collections.Generic", Arity: 1);

    private static readonly NamedTypeReference _string =
        new(Name: "String", ContainingNamespace: "System", SpecialType: SpecialType.System_String);

    private static readonly NamedTypeReference _void =
        new(Name: "Void", ContainingNamespace: "System", TypeKind: TypeKind.Struct, SpecialType: SpecialType.System_Void);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static ctx => ctx.AddSource("NotifyAttribute.g.cs", SourceText.From(Attribute, Encoding.UTF8)));

        var fields = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is VariableDeclaratorSyntax,
                static (ctx, _) => Read(ctx))
            .Where(static field => field is not null)
            .WithTrackingName(FieldsStep)
            .Collect();

        var options = context.ParseOptionsProvider.Select(static (parseOptions, _) =>
            RenderOptions.Default with { Version = ((CSharpParseOptions)parseOptions).LanguageVersion.ToCSharpVersion() });

        context.RegisterSourceOutput(fields.Combine(options), static (spc, pair) =>
        {
            foreach (var group in GroupByType(pair.Left))
            {
                var unit = Render(group.Key, group.Value);
                spc.AddSource(unit.HintName, unit.ToSourceText(pair.Right));
            }
        });
    }

    /// <summary>
    ///     The class as a new part of itself, where it lives, and the three facts the generator acts on.
    /// </summary>
    private sealed record NotifyType(
        TypeDeclaration Part,
        NamespaceDeclaration Namespace,
        bool ImplementsInterface,
        bool HasEvent,
        bool HasRaiseMethod);

    private sealed record NotifyField(
        NotifyType Type,
        FieldDeclaration Field,
        string PropertyName);

    private static NotifyField? Read(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IFieldSymbol { ContainingType: { } type } field || !type.IsPartialThroughout())
        {
            return null;
        }

        var shape = type.ToDeclaration(ReadOptions.Shape);
        var notifyPropertyChanged = context.SemanticModel.Compilation.GetTypeByMetadataName(InterfaceMetadataName);
        var declaration = field.ToDeclaration(new ReadOptions(IncludeAttributes: false));

        return new NotifyField(
            Type: new NotifyType(
                Part: shape with { Modifiers = shape.Modifiers | Modifiers.Partial },
                Namespace: type.ContainingNamespace.ToDeclaration(),
                ImplementsInterface: notifyPropertyChanged is not null && type.Implements(notifyPropertyChanged),
                HasEvent: type.GetMembers("PropertyChanged").Length > 0,
                HasRaiseMethod: type.GetMembers("OnPropertyChanged").Length > 0),
            Field: declaration,
            PropertyName: context.Attributes[0].GetArguments().NamedArgument<string>("PropertyName") ?? PropertyNameFor(declaration.Name));
    }

    private static string PropertyNameFor(string fieldName)
    {
        var trimmed = fieldName.TrimStart('_');

        return trimmed.Length == 0 ? fieldName : char.ToUpperInvariant(trimmed[0]) + trimmed.Substring(1);
    }

    private static Dictionary<NotifyType, List<NotifyField>> GroupByType(ImmutableArray<NotifyField?> fields)
    {
        // Records compare by value, so two fields of one class share a key.
        Dictionary<NotifyType, List<NotifyField>> groups = [];
        foreach (var field in fields)
        {
            if (field is null)
            {
                continue;
            }

            if (!groups.TryGetValue(field.Type, out var list))
            {
                list = [];
                groups.Add(field.Type, list);
            }

            list.Add(field);
        }

        return groups;
    }

    private static CompilationUnit Render(NotifyType type, List<NotifyField> fields)
    {
        bool isSealed = (type.Part.Modifiers & Modifiers.Sealed) != 0;
        List<MemberDeclaration> members = new(fields.Count + 2);

        if (!type.HasEvent)
        {
            members.Add(new EventDeclaration(
                DocumentationComment: "<inheritdoc/>",
                Accessibility: Accessibility.Public,
                Type: _eventHandler with { NullableAnnotation = NullableAnnotation.Annotated },
                Name: "PropertyChanged"));
        }

        if (!type.HasRaiseMethod)
        {
            members.Add(new MethodDeclaration(
                DocumentationComment: "<summary>Raises <see cref=\"PropertyChanged\"/> for <paramref name=\"propertyName\"/>.</summary>",
                Accessibility: isSealed ? Accessibility.Private : Accessibility.Protected,
                Modifiers: isSealed ? Modifiers.None : Modifiers.Virtual,
                ReturnType: _void,
                Name: "OnPropertyChanged",
                Parameters: [new ParameterDeclaration(Type: _string, Name: "propertyName")],
                Body: Snippet.Expression($"PropertyChanged?.Invoke(this, new {_eventArgs}(propertyName))")));
        }

        foreach (var (_, field, propertyName) in fields)
        {
            var comparer = _equalityComparer.Construct(field.Type);
            members.Add(new PropertyDeclaration(
                DocumentationComment: $"<summary>Gets or sets the value of <c>{field.Name}</c>, raising a change for <c>{propertyName}</c>.</summary>",
                Accessibility: Accessibility.Public,
                Type: field.Type,
                Name: propertyName,
                Getter: new AccessorDeclaration(Body: Snippet.Expression(field.Name)),
                Setter: new AccessorDeclaration(
                    Body: Snippet.From($$"""
                        if ({{comparer}}.Default.Equals({{field.Name}}, value))
                        {
                            return;
                        }

                        {{field.Name}} = value;
                        OnPropertyChanged(nameof({{propertyName}}));
                        """))));
        }

        var part = type.Part with
        {
            Interfaces = type.ImplementsInterface ? default : [_notifyPropertyChanged],
            Members = [.. members],
        };

        return new CompilationUnit(Members: [type.Namespace with { Members = [part] }], Header: FileHeader);
    }
}
