using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Redeclare;
using System;
using System.Collections.Generic;
using System.Text;

namespace EnumHelpers;

/// <summary>
///     Generates <c>ToStringFast</c>, <c>IsDefined</c> and <c>TryParse</c> extension methods for every enum marked
///     <c>[EnumHelpers]</c>, in the style the consuming project's editorconfig asks for.
/// </summary>
/// <remarks>
///     The shape of the sample. The marker attribute is a raw string literal, since nothing about it comes from the
///     input. The transform reads each enum and stops touching symbols. The output stage puts a helper class where
///     the enum's namespace is, with bodies that name the enum through holes, so qualification follows the options.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class EnumHelpersGenerator : IIncrementalGenerator
{
    /// <summary>
    ///     The name the step that reads the marked enums is tracked under, for the tests that assert what reruns
    ///     after an edit.
    /// </summary>
    public const string EnumsStep = "Enums";

    private const string AttributeMetadataName = "EnumHelpers.EnumHelpersAttribute";

    private const string FileHeader = """
        // <auto-generated/>

        #nullable enable
        """;

    // The marker attribute is the same text in every compilation, so it is a raw string literal rather than a
    // declaration. Declarations earn their keep where a type, a name or a body comes from the input.
    private const string Attribute = """
        // <auto-generated/>
        #nullable enable

        namespace EnumHelpers;

        /// <summary>
        ///     Marks an enum whose <c>ToStringFast</c>, <c>IsDefined</c> and <c>TryParse</c> helpers are generated.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
        internal sealed class EnumHelpersAttribute : global::System.Attribute
        {
            /// <summary>
            ///     Gets or sets the name of the generated static class, the enum's name plus <c>Extensions</c> when unset.
            /// </summary>
            public string? ClassName { get; set; }
        }
        """;

    // The two framework types the helpers mention. A generator can equally read them from the compilation with
    // GetSpecialType().ToTypeReference(); naming them here keeps the render stage free of symbols.
    private static readonly NamedTypeReference _string =
        new(Name: "String", ContainingNamespace: "System", SpecialType: SpecialType.System_String);

    private static readonly NamedTypeReference _boolean =
        new(Name: "Boolean", ContainingNamespace: "System", TypeKind: TypeKind.Struct, SpecialType: SpecialType.System_Boolean);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static ctx => ctx.AddSource("EnumHelpersAttribute.g.cs", SourceText.From(Attribute, Encoding.UTF8)));

        // Everything about the consumer's style in one provider. Editorconfig values are per file, so this meets
        // each enum with the tree it was read from. Neither side is a Compilation, so neither changes on a keystroke.
        var style = context.AnalyzerConfigOptionsProvider.Combine(context.ParseOptionsProvider);

        // Symbols stop in the transform. The tree rides along only as far as the next step, where it becomes an
        // equatable RenderOptions and is dropped.
        var enums = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is EnumDeclarationSyntax,
                static (ctx, _) => (Info: Read(ctx), Tree: ctx.TargetNode.SyntaxTree))
            .Combine(style)
            .Select(static (pair, _) => pair.Left.Info with
            {
                Options = RenderOptions.From(pair.Right.Left.GetOptions(pair.Left.Tree)) with
                {
                    Version = ((CSharpParseOptions)pair.Right.Right).LanguageVersion.ToCSharpVersion(),
                },
            })
            .WithTrackingName(EnumsStep);

        context.RegisterSourceOutput(enums, static (spc, info) =>
        {
            var unit = Render(info);
            spc.AddSource(unit.HintName, unit.ToSourceText(info.Options));
        });
    }

    /// <summary>
    ///     The enum as read, the one thing the attribute adds, and how to render.
    /// </summary>
    private sealed record EnumInfo(
        TypeDeclaration Enum,
        NamespaceDeclaration Namespace,
        TypeReference Type,
        string ClassName)
    {
        public RenderOptions Options { get; init; } = RenderOptions.Default;
    }

    private static EnumInfo Read(GeneratorAttributeSyntaxContext context)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;

        return new EnumInfo(
            Enum: symbol.ToDeclaration(new ReadOptions(IncludeAttributes: false)),
            Namespace: symbol.ContainingNamespace.ToDeclaration(),
            Type: symbol.ToTypeReference(),
            ClassName: context.Attributes[0].GetArguments().NamedArgument<string>("ClassName") ?? (symbol.Name + "Extensions"));
    }

    private static CompilationUnit Render(EnumInfo info)
    {
        var e = info.Type;
        var members = DistinctByValue(info.Enum.Members);

        var toStringFast = new MethodDeclaration(
            DocumentationComment: "<summary>The member's name without reflection, or <c>ToString()</c> for a value outside the enum.</summary>",
            Accessibility: Accessibility.Public,
            Modifiers: Modifiers.Static,
            ReturnType: _string,
            Name: "ToStringFast",
            Parameters: [new ParameterDeclaration(IsThis: true, Type: e, Name: "value")],
            Body: Snippet.Expression($$"""
                value switch
                {
                    {{Snippet.Concat(members, m => Snippet.From($"{e}.{m} => nameof({e}.{m}),"))}}
                    _ => value.ToString(),
                }
                """));

        var isDefined = new MethodDeclaration(
            DocumentationComment: "<summary>Whether the value is one of the enum's members.</summary>",
            Accessibility: Accessibility.Public,
            Modifiers: Modifiers.Static,
            ReturnType: _boolean,
            Name: "IsDefined",
            Parameters: [new ParameterDeclaration(IsThis: true, Type: e, Name: "value")],
            Body: Snippet.Expression($$"""
                value switch
                {
                    {{Snippet.Concat(members, m => Snippet.From($"{e}.{m} => true,"))}}
                    _ => false,
                }
                """));

        var tryParse = new MethodDeclaration(
            DocumentationComment: "<summary>Parses a member name, case-sensitively, without reflection.</summary>",
            Accessibility: Accessibility.Public,
            Modifiers: Modifiers.Static,
            ReturnType: _boolean,
            Name: "TryParse",
            Parameters: [
                new ParameterDeclaration(Type: _string with { NullableAnnotation = NullableAnnotation.Annotated }, Name: "name"),
                new ParameterDeclaration(RefKind: RefKind.Out, Type: e, Name: "value"),
            ],
            Body: Snippet.From($$"""
                switch (name)
                {
                    {{Snippet.Concat(members, Arm)}}
                    default:
                        value = default;
                        return false;
                }
                """));

        // The helper class takes the enum's place at the top of its namespace, whatever the enum was nested in: a
        // static class holding extension methods cannot itself be nested.
        var helper = new TypeDeclaration(
            DocumentationComment: Snippet.From($"<summary>Reflection-free helpers for <see cref=\"{e:f}\"/>.</summary>").ToString(),
            Accessibility: info.Enum.Accessibility == Accessibility.Public ? Accessibility.Public : Accessibility.Internal,
            Modifiers: Modifiers.Static,
            Name: info.ClassName,
            Members: [toStringFast, isDefined, tryParse]);

        return new CompilationUnit(Members: [info.Namespace with { Members = [helper] }], Header: FileHeader);

        Snippet Arm(string member)
        {
            return Snippet.From($"case nameof({e}.{member}):\n    value = {e}.{member};\n    return true;");
        }
    }

    /// <summary>
    ///     Member names, one per distinct value: an alias would make a second switch arm unreachable.
    /// </summary>
    private static List<string> DistinctByValue(EquatableArray<MemberDeclaration> members)
    {
        List<string> names = [];
        HashSet<string> values = new(StringComparer.Ordinal);
        foreach (var member in members)
        {
            if (member is EnumMemberDeclaration { Value: { } value } enumMember && values.Add(value.ToString()))
            {
                names.Add(enumMember.Name);
            }
        }

        return names;
    }
}
