using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Redeclare;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;

namespace Implement;

/// <summary>
///     Implements partial members from their definitions. A partial property marked <c>[FromEnvironment("NAME")]</c>
///     reads that environment variable, and a partial method marked <c>[Echo]</c> writes its name and arguments to
///     the console.
/// </summary>
/// <remarks>
///     The shape of the sample. The generator copies the definition with <c>ToDeclaration()</c>, sets a body, and
///     renders it into a new partial part of the type. It checks nothing. If the definition has no setter and the
///     attribute asks for one, the generator emits the setter anyway and the compiler reports the mismatch, which is
///     the compiler's job and it does it better. Output is minimally qualified, with the usings the file needs
///     collected from the declarations, so it reads the way a person would have written it.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ImplementGenerator : IIncrementalGenerator
{
    private const string FileHeader = """
        // <auto-generated/>

        #nullable enable
        """;

    private const string Attributes = """
        // <auto-generated/>
        #nullable enable

        namespace Implement;

        /// <summary>
        ///     Marks a partial property whose getter reads the named environment variable.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
        internal sealed class FromEnvironmentAttribute : global::System.Attribute
        {
            /// <summary>
            ///     Initializes a new instance of the <see cref="FromEnvironmentAttribute"/> class.
            /// </summary>
            /// <param name="name">The variable's name.</param>
            public FromEnvironmentAttribute(string name) => Name = name;

            /// <summary>
            ///     Gets the variable's name.
            /// </summary>
            public string Name { get; }

            /// <summary>
            ///     Gets or sets a value indicating whether a setter that writes the variable is generated too.
            /// </summary>
            public bool Settable { get; set; }
        }

        /// <summary>
        ///     Marks a partial method whose body writes its name and arguments to the console.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
        internal sealed class EchoAttribute : global::System.Attribute
        {
        }
        """;

    private static readonly NamedTypeReference _environment = new(Name: "Environment", ContainingNamespace: "System");

    private static readonly NamedTypeReference _console = new(Name: "Console", ContainingNamespace: "System");

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static ctx => ctx.AddSource("ImplementAttributes.g.cs", SourceText.From(Attributes, Encoding.UTF8)));

        var properties = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Implement.FromEnvironmentAttribute",
            static (node, _) => node is PropertyDeclarationSyntax,
            ReadFromEnvironment);

        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Implement.EchoAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            ReadEcho);

        var options = context.ParseOptionsProvider.Select(static (parseOptions, _) => RenderOptions.Default with
        {
            Version = ((CSharpParseOptions)parseOptions).LanguageVersion.ToCSharpVersion(),
            Qualification = Qualification.Minimal,
        });

        context.RegisterSourceOutput(properties.Collect().Combine(methods.Collect()).Combine(options), static (spc, input) =>
        {
            var ((properties, methods), options) = input;
            foreach (var group in GroupByFile(properties, methods))
            {
                var part = group.Key.Part with { Members = [.. group.Value] };
                var unit = new CompilationUnit(Members: [group.Key.Namespace with { Members = [part] }], Header: FileHeader);

                // Minimal qualification needs the usings the file's types would resolve through.
                unit = unit with { Usings = [.. CSharpRenderer.CollectNamespaces(unit)] };
                spc.AddSource(unit.HintName, unit.ToSourceText(options));
            }
        });
    }

    /// <summary>
    ///     The definition copied with a body, the part of the type it goes in, and that part's namespace.
    /// </summary>
    private sealed record Implementation(
        TypeDeclaration Part,
        NamespaceDeclaration Namespace,
        MemberDeclaration Member);

    /// <summary>
    ///     The type as a new partial part of itself: its shape, nothing a second part may not repeat, and what it is
    ///     declared in, which the reader filled in.
    /// </summary>
    private static TypeDeclaration PartOf(INamedTypeSymbol type)
    {
        var shape = type.ToDeclaration(ReadOptions.Shape);

        return shape with { Modifiers = shape.Modifiers | Modifiers.Partial };
    }

    private static Implementation ReadFromEnvironment(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        var symbol = (IPropertySymbol)ctx.TargetSymbol;
        var arguments = ctx.Attributes[0].GetArguments();

        // The name is only ever written back out, so it comes through as the literal the consumer wrote.
        var variable = arguments.ConstructorExpression("name") ?? Snippet.From($"{symbol.Name:L}");

        var definition = symbol.ToDeclaration(new ReadOptions(IncludeAttributes: false));
        var implementation = definition with
        {
            Modifiers = definition.Modifiers | Modifiers.Partial,
            Getter = new(Body: Snippet.Expression($"{_environment}.GetEnvironmentVariable({variable})")),
            Setter = arguments.NamedArgument<bool>("Settable")
                ? new(Body: Snippet.Expression($"{_environment}.SetEnvironmentVariable({variable}, value)"))
                : null,
        };

        return new(PartOf(symbol.ContainingType), symbol.ContainingNamespace.ToDeclaration(), implementation);
    }

    private static Implementation ReadEcho(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        var symbol = (IMethodSymbol)ctx.TargetSymbol;
        var definition = symbol.ToDeclaration(new ReadOptions(IncludeAttributes: false));

        string start = $"Echo {definition.Name}";
        List<Snippet> parts = [Snippet.From($"{start:L}")];
        foreach (var parameter in definition.Parameters)
        {
            parts.Add(Snippet.From($"{parameter.Name:I}"));
        }

        var body = Snippet.From($"{_console}.WriteLine({Snippet.Join(" + \", \" + ", parts)});");
        if (definition.ReturnType is not NamedTypeReference { SpecialType: SpecialType.System_Void })
        {
            body = body.Append("return default;");
        }

        return new(PartOf(symbol.ContainingType), symbol.ContainingNamespace.ToDeclaration(), definition with { Body = body });
    }

    private static Dictionary<(TypeDeclaration Part, NamespaceDeclaration Namespace), List<MemberDeclaration>> GroupByFile(
        ImmutableArray<Implementation> properties,
        ImmutableArray<Implementation> methods)
    {
        Dictionary<(TypeDeclaration Part, NamespaceDeclaration Namespace), List<MemberDeclaration>> groups = [];
        foreach (var implementation in properties.AddRange(methods))
        {
            if (!groups.TryGetValue((implementation.Part, implementation.Namespace), out var members))
            {
                members = [];
                groups.Add((implementation.Part, implementation.Namespace), members);
            }

            members.Add(implementation.Member);
        }

        return groups;
    }
}
