using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using System.Linq;

namespace Redeclare.Tests;

[TestFixture]
public sealed class ExtensionTests
{
    private const string Header = "// <auto-generated/>\n\n#nullable enable";

    private static readonly NamedTypeReference _enumerable = new(
        Name: "IEnumerable",
        ContainingNamespace: "System.Collections.Generic",
        TypeKind: TypeKind.Interface,
        Arity: 1);

    private static CompilationUnit Holding(params ExtensionDeclaration[] extensions)
    {
        return new CompilationUnit(
            Header: Header,
            Members: [
                new NamespaceDeclaration(
                    Name: "Sample",
                    Members: [
                        new TypeDeclaration(
                            Accessibility: Accessibility.Public,
                            Modifiers: Modifiers.Static,
                            Name: "Extensions",
                            Members: [.. extensions]),
                    ]),
            ]);
    }

    [Test]
    public void Render_ExtensionBlockWithReceiverAndTypeParameter_CompilesAndSpellsIt()
    {
        var block = new ExtensionDeclaration(
            Receiver: new ParameterDeclaration(Type: _enumerable.Construct(Types.T), Name: "source"),
            TypeParameters: [new TypeParameterDeclaration(Name: "T", HasReferenceTypeConstraint: true)],
            Members: [
                new PropertyDeclaration(
                    Accessibility: Accessibility.Public,
                    Type: Types.Boolean,
                    Name: "IsEmpty",
                    Getter: new AccessorDeclaration(Body: Snippet.Expression("!source.GetEnumerator().MoveNext()")),
                    Setter: null),
                new MethodDeclaration(
                    Accessibility: Accessibility.Public,
                    Modifiers: Modifiers.Static,
                    ReturnType: _enumerable.Construct(Types.T),
                    Name: "Empty",
                    Body: Snippet.Expression("[]")),
            ]);

        string text = Holding(block).Render();
        Compiling.AssertCompiles(text);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("    extension<T>(global::System.Collections.Generic.IEnumerable<T> source) where T : class\n    {\n"));
            Assert.That(text, Does.Contain("        public bool IsEmpty => !source.GetEnumerator().MoveNext();\n"));
            Assert.That(text, Does.Contain("        public static global::System.Collections.Generic.IEnumerable<T> Empty()\n"));
        }
    }

    [Test]
    public void Render_UnnamedReceiver_WritesTheTypeAlone()
    {
        var block = new ExtensionDeclaration(
            Receiver: new ParameterDeclaration(Type: Types.String, Name: ""),
            Members: [
                new PropertyDeclaration(
                    Accessibility: Accessibility.Public,
                    Modifiers: Modifiers.Static,
                    Type: Types.String,
                    Name: "Greeting",
                    Getter: new AccessorDeclaration(Body: Snippet.Expression("\"hi\"")),
                    Setter: null),
            ]);

        string text = Holding(block).Render();
        Compiling.AssertCompiles(text);

        Assert.That(text, Does.Contain("    extension(string)\n    {\n        public static string Greeting => \"hi\";\n    }"));
    }

    [Test]
    public void Render_RefReceiver_WritesTheModifier()
    {
        var block = new ExtensionDeclaration(
            Receiver: new ParameterDeclaration(Type: Types.Int32, Name: "value", RefKind: RefKind.Ref),
            Members: [
                new MethodDeclaration(
                    Accessibility: Accessibility.Public,
                    ReturnType: Types.Void,
                    Name: "Increment",
                    Body: "value++;"),
            ]);

        string text = Holding(block).Render();
        Compiling.AssertCompiles(text);

        Assert.That(text, Does.Contain("extension(ref int value)"));
    }

    [Test]
    public void Render_ExtensionBlockBelowCSharp14_RendersAndLeavesTheErrorToTheCompiler()
    {
        var block = new ExtensionDeclaration(Receiver: new ParameterDeclaration(Type: Types.String, Name: "s"));

        var text = Holding(block).Render(RenderOptions.Default with { Version = CSharpVersion.CSharp13 });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("extension(string s)"));
            Assert.That(
                Compiling.Compile(text, LanguageVersion.CSharp13).GetDiagnostics().Select(d => d.Id),
                Does.Contain("CS9260"),
                "CS9260 names the feature and the version it needs, which is the error a consumer should see");
        }
    }

    [Test]
    public void Render_ExtensionBlockOutsideAStaticClass_Throws()
    {
        var block = new ExtensionDeclaration(Receiver: new ParameterDeclaration(Type: Types.String, Name: "s"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "NotStatic", Members: [block])]);

        Assert.That(() => unit.Render(), Throws.TypeOf<RenderException>().With.Message.Contains("static class"));
    }

    [Test]
    public void Render_ExtensionBlockHoldingAField_Throws()
    {
        var block = new ExtensionDeclaration(
            Receiver: new ParameterDeclaration(Type: Types.String, Name: "s"),
            Members: [new FieldDeclaration(Type: Types.Int32, Name: "_count")]);

        Assert.That(() => Holding(block).Render(), Throws.TypeOf<RenderException>().With.Message.Contains("methods, operators and properties"));
    }

    [Test]
    public void ToDeclaration_StaticClassWithExtensionBlocks_ReadsThemAndRendersThemBack()
    {
        var compilation = Compiling.AssertCompiles("""
            namespace Sample;

            public static class Extensions
            {
                extension<T>(System.Collections.Generic.IEnumerable<T> source) where T : class
                {
                    public int Count2 => 0;
                    public T? FirstOrNull() => null;
                }

                extension(string)
                {
                    public static string Greeting => "hi";
                }

                public static int Plain(this int x) => x;
            }
            """);
        var extensions = compilation.Type("Sample.Extensions").ToDeclaration();
        var blocks = extensions.Members.OfType<ExtensionDeclaration>().ToList();
        var text = compilation.Type("Sample.Extensions").ToFile().Render();

        using (Assert.EnterMultipleScope())
        {
            Assert.That(blocks, Has.Count.EqualTo(2));
            Assert.That(blocks[0].Receiver.Name, Is.EqualTo("source"));
            Assert.That(blocks[0].TypeParameters.Single().HasReferenceTypeConstraint, Is.True);
            Assert.That(blocks[0].Members.Select(m => m.GetType()), Is.EqualTo(new[] { typeof(PropertyDeclaration), typeof(MethodDeclaration) }));
            Assert.That(blocks[1].Receiver.Name, Is.Empty);
            Assert.That(extensions.Members.OfType<MethodDeclaration>().Single().Name, Is.EqualTo("Plain"), "the implementation methods are the compiler's");
            Assert.That(text, Does.Contain("extension<T>(global::System.Collections.Generic.IEnumerable<T> source) where T : class"));
            Assert.That(text, Does.Contain("extension(string)"));
            Assert.That(text, Does.Contain("public static string Greeting { get; }"));
        }
    }

    [Test]
    public void ToDeclaration_ExtensionBlockItself_Throws()
    {
        var compilation = Compiling.AssertCompiles("public static class E { extension(int x) { public int Twice => x * 2; } }");
        var block = compilation.Type("E").GetTypeMembers().Single();

        using (Assert.EnterMultipleScope())
        {
            Assert.That(() => block.ToDeclaration(), Throws.ArgumentException.With.Message.Contains("ToExtensionDeclaration"));
            Assert.That(block.ToExtensionDeclaration().Receiver.Type, Is.EqualTo(Types.Int32));
            Assert.That(() => compilation.Type("E").ToExtensionDeclaration(), Throws.ArgumentException);
        }
    }
}
