using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using System;
using System.Linq;

namespace Redeclare.Tests;

/// <summary>
///     Covers the token every user-defined operator reads back as, and the ones that have no typed declaration.
/// </summary>
[TestFixture]
public sealed class OperatorTests
{
    private const string Source = """
        public class V
        {
            public static V operator +(V a, V b) => a;
            public static V operator -(V a, V b) => a;
            public static V operator *(V a, V b) => a;
            public static V operator /(V a, V b) => a;
            public static V operator %(V a, V b) => a;
            public static V operator &(V a, V b) => a;
            public static V operator |(V a, V b) => a;
            public static V operator ^(V a, V b) => a;
            public static V operator <<(V a, int b) => a;
            public static V operator >>(V a, int b) => a;
            public static V operator >>>(V a, int b) => a;
            public static bool operator ==(V a, V b) => true;
            public static bool operator !=(V a, V b) => false;
            public static bool operator <(V a, V b) => true;
            public static bool operator >(V a, V b) => true;
            public static bool operator <=(V a, V b) => true;
            public static bool operator >=(V a, V b) => true;
            public static V operator -(V a) => a;
            public static V operator +(V a) => a;
            public static bool operator !(V a) => true;
            public static V operator ~(V a) => a;
            public static V operator ++(V a) => a;
            public static V operator --(V a) => a;
            public static bool operator true(V a) => true;
            public static bool operator false(V a) => false;
            public static implicit operator int(V a) => 0;
            public static explicit operator long(V a) => 0;
            public static V operator checked +(V a, V b) => a;
            public static V operator checked -(V a) => a;
        }
        """;

    private static CSharpCompilation Compilation => field ??= Compiling.AssertCompiles(Source);

    private static string[] Names => [.. Compilation.Type("V").ToDeclaration().Members.OfType<MethodDeclaration>().Select(m => m.Name)];

    [Test]
    public void ToDeclaration_EveryOverloadableOperator_ReadsAsItsToken()
    {
        Assert.That(
            Names.Where(n => n.StartsWith("operator", StringComparison.Ordinal)).Order(StringComparer.Ordinal),
            Is.EqualTo(new[]
            {
                "operator !",
                "operator !=",
                "operator %",
                "operator &",
                "operator *",
                "operator +",
                "operator +",
                "operator ++",
                "operator -",
                "operator -",
                "operator --",
                "operator /",
                "operator <",
                "operator <<",
                "operator <=",
                "operator ==",
                "operator >",
                "operator >=",
                "operator >>",
                "operator >>>",
                "operator ^",
                "operator false",
                "operator true",
                "operator |",
                "operator ~",
            }));
    }

    [Test]
    public void Render_ReadOperators_CompileAgain()
    {
        var type = Compilation.Type("V").ToDeclaration();
        var withBodies = type with
        {
            Members = [.. type.Members.Select(m => m switch
            {
                MethodDeclaration { ReturnType: NamedTypeReference { SpecialType: SpecialType.System_Boolean } } method
                    => method with { Body = Snippet.Expression("true") },
                MethodDeclaration method => method with { Body = Snippet.Expression("a") },
                _ => m,
            })],
        };

        var text = new CompilationUnit(Members: [withBodies], Header: "// <auto-generated/>").Render();

        Assert.That(text, Does.Contain("public static V operator >>>(V a, int b)"));
        Compiling.AssertCompiles(text);
    }

    [Test]
    public void ToDeclaration_CheckedOperator_Throws()
    {
        var @checked = Compilation.Type("V").GetMembers("op_CheckedAddition").OfType<IMethodSymbol>().Single();

        Assert.That(() => @checked.ToDeclaration(), Throws.InstanceOf<NotSupportedException>());
    }
}
