using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;

namespace Redeclare.Tests;

[TestFixture]
public sealed class RenderOptionsTests
{
    private const string Header = "// <auto-generated/>\n\n#nullable enable";

    [Test]
    public void Render_MethodPreference_DecidesArrowOrBlock()
    {
        var method = new MethodDeclaration(Accessibility: Accessibility.Public, ReturnType: Types.Int32, Name: "Get", Body: Snippet.Expression("1"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])], Header: Header);

        var never = unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.Never });
        var always = unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.WhenPossible });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(never, Does.Contain("public int Get()\n    {\n        return 1;\n    }"));
            Assert.That(always, Does.Contain("public int Get() => 1;"));
        }
    }

    [Test]
    public void Render_UnderCSharp5_DegradesFileScopedNamespaceAndArrowsToBlocks()
    {
        var property = new PropertyDeclaration(
            Type: Types.Int32,
            Name: "P",
            Getter: new AccessorDeclaration(Body: Snippet.Expression("1")),
            Setter: null);
        var unit = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "N", Members: [new TypeDeclaration(Name: "C", Members: [property])])],
            Header: "// <auto-generated/>");

        var old = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp5 });
        Compiling.AssertCompiles(old, LanguageVersion.CSharp5);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(old, Does.Not.Contain("#nullable"));
            Assert.That(old, Does.Contain("namespace N\n{\n"));
            Assert.That(old, Does.Contain("int P\n        {\n            get\n            {\n                return 1;\n            }\n        }"));
        }
    }

    [Test]
    public void Render_FeatureBelowItsVersion_Throws()
    {
        var recordStruct = new CompilationUnit(Members: [new TypeDeclaration(TypeKind: TypeKind.Struct, IsRecord: true, Name: "P")], Header: Header);
        var required = new CompilationUnit(
            Members: [new TypeDeclaration(Name: "C", Members: [new FieldDeclaration(Modifiers: Modifiers.Required, Type: Types.Int32, Name: "X")])],
            Header: Header);
        var init = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Members: [
                        new PropertyDeclaration(
                            Type: Types.Int32,
                            Name: "X",
                            Getter: new AccessorDeclaration(),
                            Setter: new AccessorDeclaration(IsInitOnly: true)),
                    ]),
            ],
            Header: Header);
        var allows = new CompilationUnit(
            Members: [new TypeDeclaration(Name: "C", TypeParameters: [new TypeParameterDeclaration(Name: "T", AllowsRefLikeType: true)])],
            Header: Header);
        var c = new NamedTypeReference(Name: "C");
        var shift = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Members: [
                        new MethodDeclaration(
                            Modifiers: Modifiers.Static,
                            ReturnType: c,
                            Name: "operator >>>",
                            Parameters: [new ParameterDeclaration(Type: c, Name: "a"), new ParameterDeclaration(Type: Types.Int32, Name: "b")],
                            Body: Snippet.Expression("a")),
                    ]),
            ],
            Header: Header);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(
                () => recordStruct.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp9 }),
                Throws.TypeOf<RenderException>().With.Message.Contains("record struct").And.Message.Contains("C# 10"));
            Assert.That(
                () => required.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp10 }),
                Throws.TypeOf<RenderException>().With.Message.Contains("'required'"));
            Assert.That(
                () => init.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp8 }),
                Throws.TypeOf<RenderException>().With.Message.Contains("init"));
            Assert.That(
                () => allows.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp12 }),
                Throws.TypeOf<RenderException>().With.Message.Contains("allows ref struct"));
            Assert.That(allows.Render(), Does.Contain("class C<T> where T : allows ref struct"));
            Assert.That(
                () => shift.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp10 }),
                Throws.TypeOf<RenderException>().With.Message.Contains("unsigned right shift"));
            Assert.That(shift.Render(), Does.Contain("static C operator >>>(C a, int b)"));
            Assert.That(() => recordStruct.Render(), Throws.Nothing);
        }
    }

    [Test]
    public void Render_OverridesOnAType_ApplyToItAndItsMembersOnly()
    {
        var inner = new MethodDeclaration(ReturnType: Types.Int32, Name: "Get", Body: Snippet.Expression("1"));
        var type = new TypeDeclaration(
            Name: "C",
            Overrides: new RenderOverrides(Methods: ExpressionBodyPreference.WhenPossible, Qualification: Qualification.Minimal),
            Members: [inner, new FieldDeclaration(Type: Types.List.Construct(Types.Int32), Name: "_l")]);
        var unit = new CompilationUnit(Members: [type, new TypeDeclaration(Name: "D", Members: [inner])], Header: Header);

        var text = unit.Render();

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("class C\n{\n    int Get() => 1;\n\n    List<int> _l;\n}"));
            Assert.That(text, Does.Contain("class D\n{\n    int Get()\n    {\n        return 1;\n    }\n}"));
        }
    }

    [Test]
    public void Equals_DifferentOverrides_IsFalse()
    {
        var a = new MethodDeclaration(Name: "M", ReturnType: Types.Void);
        var b = a with { Overrides = new RenderOverrides(Methods: ExpressionBodyPreference.WhenPossible) };
        var c = a with { Overrides = new RenderOverrides(Methods: ExpressionBodyPreference.WhenPossible) };

        using (Assert.EnterMultipleScope())
        {
            Assert.That(a, Is.Not.EqualTo(b));
            Assert.That(b, Is.EqualTo(c));
        }
    }

    [Test]
    public void Render_AccessorArrowUnderCSharp6_BecomesABlock()
    {
        var unit = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Members: [
                        new FieldDeclaration(Type: Types.Int32, Name: "_x"),
                        new PropertyDeclaration(
                            Type: Types.Int32,
                            Name: "P",
                            Getter: new AccessorDeclaration(Body: Snippet.Expression("_x")),
                            Setter: new AccessorDeclaration(Body: Snippet.Expression("_x = value"))),
                    ]),
            ]);

        var six = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp6 });
        var seven = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp7 });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(six, Does.Contain("get\n        {\n            return _x;"), "an accessor arrow needs C# 7");
            Assert.That(seven, Does.Contain("get => _x;"));
        }

        Compiling.AssertCompiles(six, LanguageVersion.CSharp6);
    }

    [Test]
    public void Render_VersionWithoutMinor_IsNamedWithoutOne()
    {
        var unit = new CompilationUnit(Members: [new TypeDeclaration(TypeKind: TypeKind.Struct, IsRecord: true, Name: "P")]);

        Assert.That(
            () => unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp7_2 }),
            Throws.TypeOf<RenderException>().With.Message.Contains("C# 10").And.Message.Contains("C# 7.2"));
    }
}
