using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;

namespace Redeclare.Tests;

[TestFixture]
public sealed class RenderOptionsTests
{
    private const string Header = "// <auto-generated/>\n\n#nullable enable";

    [Test]
    public void Render_MethodPreference_DecidesArrowOrBlock()
    {
        var method = new MethodDeclaration(Accessibility: Accessibility.Public, ReturnType: Types.Int32, Name: "Get", Body: Snippet.Expression("1"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])], Header: Header);

        var never = unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.Never });
        var always = unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.WhenPossible });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(never, Does.Contain("public int Get()\n    {\n        return 1;\n    }"));
            Assert.That(always, Does.Contain("public int Get() => 1;"));
        }
    }

    [Test]
    public void Render_UnderCSharp5_DegradesFileScopedNamespaceAndArrowsToBlocks()
    {
        var property = new PropertyDeclaration(
            Type: Types.Int32,
            Name: "P",
            Getter: new AccessorDeclaration(Body: Snippet.Expression("1")),
            Setter: null);
        var unit = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "N", Members: [new TypeDeclaration(Name: "C", Members: [property])])],
            Header: "// <auto-generated/>");

        var old = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp5 });
        Compiling.AssertCompiles(old, LanguageVersion.CSharp5);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(old, Does.Not.Contain("#nullable"));
            Assert.That(old, Does.Contain("namespace N\n{\n"));
            Assert.That(old, Does.Contain("int P\n        {\n            get\n            {\n                return 1;\n            }\n        }"));
        }
    }

    [Test]
    public void Render_AccessorArrowUnderCSharp6_BecomesABlock()
    {
        var unit = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Members: [
                        new FieldDeclaration(Type: Types.Int32, Name: "_x"),
                        new PropertyDeclaration(
                            Type: Types.Int32,
                            Name: "P",
                            Getter: new AccessorDeclaration(Body: Snippet.Expression("_x")),
                            Setter: new AccessorDeclaration(Body: Snippet.Expression("_x = value"))),
                    ]),
            ]);

        var six = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp6 });
        var seven = unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp7 });

        using (Assert.EnterMultipleScope())
        {
            Assert.That(six, Does.Contain("get\n        {\n            return _x;"), "an accessor arrow needs C# 7");
            Assert.That(seven, Does.Contain("get => _x;"));
        }

        Compiling.AssertCompiles(six, LanguageVersion.CSharp6);
    }

    [Test]
    public void Render_NativeIntegerUnderCSharp8_WritesTheTypeByName()
    {
        var native = new NamedTypeReference(
            Name: "IntPtr",
            ContainingNamespace: "System",
            TypeKind: TypeKind.Struct,
            SpecialType: SpecialType.System_IntPtr,
            IsNativeIntegerType: true);
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [new FieldDeclaration(Type: native, Name: "_n")])], Header: Header);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp8 }), Does.Contain("global::System.IntPtr _n;"));
            Assert.That(unit.Render(RenderOptions.Default with { Version = CSharpVersion.CSharp9 }), Does.Contain("nint _n;"));
        }
    }
}
