using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;

namespace Redeclare.Tests;

[TestFixture]
public sealed class RenderTests
{
    private const string Header = "// <auto-generated/>\n\n#nullable enable";

    [Test]
    public void Render_StaticPropertyWithMultiLineInitializer_WritesTheWholeFile()
    {
        var options = new NamedTypeReference(Name: "Options", ContainingNamespace: "My");
        var sectionShape = new NamedTypeReference(Name: "SectionShape", ContainingType: options);
        var nested = new NamedTypeReference(Name: "Nested", ContainingNamespace: "My");
        var shape = new PropertyDeclaration(
            DocumentationComment: """
                <summary>
                    Gets the options the type declares.
                </summary>
                """,
            Accessibility: Accessibility.Internal,
            Modifiers: Modifiers.Static | Modifiers.New,
            Type: sectionShape,
            Name: "Shape",
            Initializer: Snippet.From($"""
                new(
                    ("timeout", null),
                    ("nested", {nested}.Shape))
                """),
            Getter: new AccessorDeclaration(),
            Setter: null);
        var unit = new CompilationUnit(
            Members: [
                new NamespaceDeclaration(
                    Name: "My",
                    Members: [new TypeDeclaration(Name: "Options", Modifiers: Modifiers.Partial, Members: [shape])]),
            ],
            Header: Header);

        Assert.That(unit.Render(), Is.EqualTo("""
            // <auto-generated/>

            #nullable enable

            namespace My;

            partial class Options
            {
                /// <summary>
                ///     Gets the options the type declares.
                /// </summary>
                internal static new global::My.Options.SectionShape Shape { get; } = new(
                    ("timeout", null),
                    ("nested", global::My.Nested.Shape));
            }

            """.ReplaceLineEndings("\n")));
    }

    [Test]
    public void Render_EveryMemberKind_CompilesAndSpellsEachAsCSharpDoes()
    {
        var thing = new NamedTypeReference(Name: "Thing", ContainingNamespace: "Sample", Arity: 1).Construct(Types.T);
        var tResult = new TypeParameterReference(Name: "TResult");
        var unit = new CompilationUnit(
            Members: [
                new NamespaceDeclaration(
                    Name: "Sample",
                    Members: [
                    new TypeDeclaration(
                        DocumentationComment: "<summary>A thing.</summary>",
                        Attributes: [new AttributeSpecification(Type: Types.SerializableAttribute)],
                        Accessibility: Accessibility.Public,
                        Modifiers: Modifiers.Sealed | Modifiers.Partial,
                        Name: "Thing",
                        TypeParameters: [new TypeParameterDeclaration(Name: "T", HasReferenceTypeConstraint: true, HasConstructorConstraint: true)],
                        Interfaces: [Types.IDisposable],
                        Members: [
                            new FieldDeclaration(
                                Accessibility: Accessibility.Private,
                                Modifiers: Modifiers.ReadOnly,
                                Type: Types.List.Construct(Types.T),
                                Name: "_items",
                                Initializer: "[]"),
                            new FieldDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Const,
                                Type: Types.String,
                                Name: "Name",
                                Initializer: "\"thing\""),
                            new EventDeclaration(Accessibility: Accessibility.Public, Type: Types.Nullable(Types.EventHandler), Name: "Changed"),
                            new ConstructorDeclaration(
                                Accessibility: Accessibility.Public,
                                Parameters: [new ParameterDeclaration(Type: Types.Int32, Name: "count", Default: "0")],
                                Body: "_ = count;"),
                            new PropertyDeclaration(
                                Accessibility: Accessibility.Public,
                                Type: Types.Int32,
                                Name: "Count",
                                Getter: new AccessorDeclaration(Body: Snippet.Expression("_items.Count")),
                                Setter: null),
                            new PropertyDeclaration(
                                Accessibility: Accessibility.Public,
                                Type: Types.Nullable(Types.String),
                                Name: "Label",
                                Getter: new AccessorDeclaration(),
                                Setter: new AccessorDeclaration(IsInitOnly: true)),
                            new PropertyDeclaration(
                                Accessibility: Accessibility.Public,
                                Type: Types.Int32,
                                Name: "Total",
                                Getter: new AccessorDeclaration(),
                                Setter: new AccessorDeclaration(Accessibility: Accessibility.Private),
                                Initializer: "1"),
                            new PropertyDeclaration(
                                Accessibility: Accessibility.Public,
                                Type: Types.T,
                                Name: "this",
                                Parameters: [new ParameterDeclaration(Type: Types.Int32, Name: "index")],
                                Getter: new AccessorDeclaration(Body: Snippet.Expression("_items[index]")),
                                Setter: new AccessorDeclaration(Body: "_items[index] = value;")),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                ReturnType: tResult,
                                Name: "Map",
                                TypeParameters: [new TypeParameterDeclaration(Name: "TResult")],
                                Parameters: [
                                    new ParameterDeclaration(Type: Types.Func2.Construct(Types.T, tResult), Name: "map"),
                                    new ParameterDeclaration(Type: Types.T, Name: "item"),
                                ],
                                Body: Snippet.Expression("map(item)")),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Static,
                                ReturnType: Types.Boolean,
                                Name: "TryGet",
                                Parameters: [
                                    new ParameterDeclaration(
                                        RefKind: RefKind.Out,
                                        Type: Types.T with { NullableAnnotation = NullableAnnotation.Annotated },
                                        Name: "value"),
                                    new ParameterDeclaration(IsParams: true, Type: new ArrayTypeReference(ElementType: Types.Int32), Name: "keys"),
                                ],
                                Body: """
                                    value = default;
                                    return keys.Length > 0;
                                    """),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                ReturnType: Types.Void,
                                Name: "Dispose",
                                Body: "Changed = null;"),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Static,
                                ReturnType: Types.Boolean,
                                Name: "operator ==",
                                Parameters: [new ParameterDeclaration(Type: thing, Name: "a"), new ParameterDeclaration(Type: thing, Name: "b")],
                                Body: Snippet.Expression("ReferenceEquals(a, b)")),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Static,
                                ReturnType: Types.Boolean,
                                Name: "operator !=",
                                Parameters: [new ParameterDeclaration(Type: thing, Name: "a"), new ParameterDeclaration(Type: thing, Name: "b")],
                                Body: Snippet.Expression("!(a == b)")),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Override,
                                ReturnType: Types.Boolean,
                                Name: "Equals",
                                Parameters: [new ParameterDeclaration(Type: Types.Nullable(Types.Object), Name: "obj")],
                                Body: Snippet.Expression("ReferenceEquals(this, obj)")),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                Modifiers: Modifiers.Override,
                                ReturnType: Types.Int32,
                                Name: "GetHashCode",
                                Body: Snippet.Expression("0")),
                            new RawMemberDeclaration(Text: "~Thing() { }"),
                            new TypeDeclaration(
                                Accessibility: Accessibility.Public,
                                TypeKind: TypeKind.Enum,
                                Name: "Mode",
                                EnumUnderlyingType: Types.Byte,
                                Members: [
                                    new EnumMemberDeclaration(Name: "Off"),
                                    new EnumMemberDeclaration(Name: "On", Value: "3", DocumentationComment: "<summary>On.</summary>"),
                                ]),
                            new TypeDeclaration(
                                Accessibility: Accessibility.Public,
                                TypeKind: TypeKind.Struct,
                                IsRecord: true,
                                Modifiers: Modifiers.ReadOnly,
                                Name: "Point",
                                ParameterList: [
                                    new ParameterDeclaration(Type: Types.Int32, Name: "X"),
                                    new ParameterDeclaration(Type: Types.Int32, Name: "Y"),
                                ]),
                            new TypeDeclaration(
                                Accessibility: Accessibility.Public,
                                TypeKind: TypeKind.Interface,
                                Name: "IVisitor",
                                TypeParameters: [new TypeParameterDeclaration(Name: "TIn", Variance: VarianceKind.In)],
                                Members: [
                                    new MethodDeclaration(
                                        Name: "Visit",
                                        Parameters: [new ParameterDeclaration(Type: new TypeParameterReference(Name: "TIn"), Name: "value")],
                                        ReturnType: Types.Void),
                                ]),
                        ]),
                ]),
            ],
            Header: Header);

        var text = unit.Render();
        Compiling.AssertCompiles(text);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("public sealed partial class Thing<T> : global::System.IDisposable where T : class, new()"));
            Assert.That(text, Does.Contain("private readonly global::System.Collections.Generic.List<T> _items = [];"));
            Assert.That(text, Does.Contain("public const string Name = \"thing\";"));
            Assert.That(text, Does.Contain("public event global::System.EventHandler? Changed;"));
            Assert.That(text, Does.Contain("public Thing(int count = 0)\n    {\n        _ = count;\n    }"));
            Assert.That(text, Does.Contain("public int Count => _items.Count;"));
            Assert.That(text, Does.Contain("public string? Label { get; init; }"));
            Assert.That(text, Does.Contain("public int Total { get; private set; } = 1;"));
            Assert.That(
                text,
                Does.Contain(
                    "public T this[int index]\n    {\n        get => _items[index];\n        set\n        {\n"
                    + "            _items[index] = value;\n        }\n    }"));
            Assert.That(
                text,
                Does.Contain("public TResult Map<TResult>(global::System.Func<T, TResult> map, T item)\n    {\n        return map(item);\n    }"));
            Assert.That(text, Does.Contain("public static bool TryGet(out T? value, params int[] keys)"));
            Assert.That(
                text,
                Does.Contain("public enum Mode : byte\n    {\n        Off,\n        /// <summary>On.</summary>\n        On = 3,\n    }"));
            Assert.That(text, Does.Contain("public readonly record struct Point(int X, int Y)\n    {\n    }"));
            Assert.That(text, Does.Contain("public interface IVisitor<in TIn>\n    {\n        void Visit(TIn value);\n    }"));
        }
    }

    [Test]
    public void Render_DelegateRefMembersAndEventAccessors_Compile()
    {
        var markAttribute = new NamedTypeReference(Name: "MarkAttribute", ContainingNamespace: "Sample");
        var unit = new CompilationUnit(
            Members: [
                new NamespaceDeclaration(
                    Name: "Sample",
                    Members: [
                    new TypeDeclaration(
                        Accessibility: Accessibility.Public,
                        Name: "Callback",
                        TypeKind: TypeKind.Delegate,
                        TypeParameters: [new TypeParameterDeclaration(Name: "T", HasValueTypeConstraint: true)],
                        ReturnType: Types.Boolean,
                        ParameterList: [
                            new ParameterDeclaration(Type: Types.T, Name: "value"),
                            new ParameterDeclaration(RefKind: RefKind.Out, Type: Types.String, Name: "text"),
                        ]),
                    new TypeDeclaration(
                        Accessibility: Accessibility.Public,
                        Modifiers: Modifiers.Ref,
                        TypeKind: TypeKind.Struct,
                        Name: "Holder",
                        TypeParameters: [new TypeParameterDeclaration(Name: "T", Attributes: [new AttributeSpecification(Type: markAttribute)])],
                        Members: [
                            new FieldDeclaration(Accessibility: Accessibility.Public, RefKind: RefKind.Ref, Type: Types.Int32, Name: "Slot"),
                            new PropertyDeclaration(
                                Accessibility: Accessibility.Public,
                                RefKind: RefKind.RefReadOnly,
                                Type: Types.Int32,
                                Name: "Value",
                                Getter: new AccessorDeclaration(Body: Snippet.Expression("ref Slot")),
                                Setter: null),
                            new MethodDeclaration(
                                Accessibility: Accessibility.Public,
                                RefKind: RefKind.Ref,
                                ReturnType: Types.Int32,
                                Name: "Borrow",
                                Body: Snippet.Expression("ref Slot")),
                            new EventDeclaration(
                                Accessibility: Accessibility.Public,
                                Type: Types.Action,
                                Name: "Changed",
                                Adder: new AccessorDeclaration(Body: "_ = value;"),
                                Remover: new AccessorDeclaration(Body: "_ = value;")),
                        ]),
                ]),
            ],
            Header: Header);

        string text = unit.Render(RenderOptions.Default);
        Compiling.AssertCompiles(text, LanguageVersion.Latest, "namespace Sample { public sealed class MarkAttribute : System.Attribute { } }");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("public delegate bool Callback<T>(T value, out string text) where T : struct;"));
            Assert.That(text, Does.Contain("public ref struct Holder<[global::Sample.MarkAttribute] T>"));
            Assert.That(text, Does.Contain("public ref int Slot;"));
            Assert.That(text, Does.Contain("public ref readonly int Value => ref Slot;"));
            Assert.That(text, Does.Contain("public ref int Borrow()"));
            Assert.That(
                text,
                Does.Contain("public event global::System.Action Changed\n    {\n        add\n        {\n            _ = value;\n        }"));
        }
    }

    [Test]
    public void Render_MultiLineExpressionBody_ContinuesIndentedUnderTheHead()
    {
        var method = new MethodDeclaration(ReturnType: Types.Int32, Name: "Get", Body: Snippet.Expression("a\n+ b"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])], Header: Header);

        var text = unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.WhenPossible });

        Assert.That(text, Does.Contain("    int Get() =>\n        a\n        + b;\n"));
    }

    [Test]
    public void Render_ExpressionBodyWithNoExpression_Throws()
    {
        var method = new MethodDeclaration(Name: "M", ReturnType: Types.Void, Body: Snippet.Expression(""));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])], Header: Header);

        Assert.That(() => unit.Render(), Throws.TypeOf<RenderException>().With.Message.Contains("no expression"));
    }

    [Test]
    public void Render_StatementBody_StaysABlockWhateverThePreference()
    {
        var statements = new MethodDeclaration(Name: "M", Body: "a();", ReturnType: Types.Void);
        var expression = new MethodDeclaration(Name: "M", Body: Snippet.Expression("a()"), ReturnType: Types.Void);
        var arrows = RenderOptions.Default with { Methods = ExpressionBodyPreference.WhenPossible };

        using (Assert.EnterMultipleScope())
        {
            Assert.That(Unit(statements).Render(arrows), Does.Contain("void M()\n    {\n        a();\n    }"));
            Assert.That(Unit(expression).Render(arrows), Does.Contain("void M() => a();"));
            Assert.That(Unit(expression).Render(RenderOptions.Default), Does.Contain("void M()\n    {\n        a();\n    }"));
        }

        static CompilationUnit Unit(MethodDeclaration method)
        {
            return new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])], Header: Header);
        }
    }

    [Test]
    public void CollectNamespaces_TypesAcrossTheFile_ListsTheirNamespacesSorted()
    {
        var unit = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Interfaces: [Types.IDisposable],
                    TypeParameters: [new TypeParameterDeclaration(Name: "T", ConstraintTypes: [Types.Stream])],
                    Members: [
                        new FieldDeclaration(Type: Types.List.Construct(Types.StringBuilder), Name: "_a"),
                        new MethodDeclaration(
                            Name: "M",
                            Parameters: [new ParameterDeclaration(Type: new ArrayTypeReference(ElementType: Types.Int32), Name: "xs")],
                            ReturnType: Types.Void),
                    ]),
            ],
            Header: Header);

        Assert.That(CSharpRenderer.CollectNamespaces(unit), Is.EqualTo(new[] { "System", "System.Collections.Generic", "System.IO", "System.Text" }));
    }

    [Test]
    public void CollectNamespaces_HoleInsideAnEventAccessor_IsCounted()
    {
        var unit = new CompilationUnit(
            Members: [
                new TypeDeclaration(
                    Name: "C",
                    Members: [
                        new EventDeclaration(
                            Type: Types.EventHandler,
                            Name: "Changed",
                            Adder: new AccessorDeclaration(Body: Snippet.From($"{Types.Console}.WriteLine();")),
                            Remover: new AccessorDeclaration(Body: Snippet.Empty)),
                    ]),
            ]);

        Assert.That(CSharpRenderer.CollectNamespaces(unit), Is.EqualTo(new[] { "System" }));
    }

    [Test]
    public void Render_HeaderAndUsings_WritesThemAsGivenInOrder()
    {
        var unit = new CompilationUnit(
            Header: """
                // <auto-generated/>

                #nullable enable

                #pragma warning disable CS1591
                #pragma warning disable CS0618
                """,
            Usings: ["System"],
            Members: [new TypeDeclaration(Name: "C")]);

        Assert.That(
            unit.Render(),
            Does.StartWith(
                "// <auto-generated/>\n\n#nullable enable\n\n#pragma warning disable CS1591\n#pragma warning disable CS0618\n\n"
                + "using System;\n\nclass C"));
    }

    [Test]
    public void Render_SeveralNamespacesAndTypes_UsesBlocksAndNestsThem()
    {
        var file = new CompilationUnit(
            Members: [
                new TypeDeclaration(Name: "Global"),
                new NamespaceDeclaration(
                    Name: "A",
                    Members: [
                        new TypeDeclaration(Name: "InA"),
                        new NamespaceDeclaration(Name: "B.C", Members: [new TypeDeclaration(Name: "InBC")]),
                    ]),
                new NamespaceDeclaration(Name: "D", Members: [new TypeDeclaration(TypeKind: TypeKind.Struct, Name: "InD")]),
            ],
            Header: Header);

        string text = file.Render(RenderOptions.Default);
        Compiling.AssertCompiles(text);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("class Global"));
            Assert.That(text, Does.Contain("namespace A\n{"));
            Assert.That(text, Does.Contain("    namespace B.C\n    {"));
            Assert.That(text, Does.Contain("        class InBC"));
            Assert.That(text, Does.Contain("namespace D\n{"));
            Assert.That(text, Does.Not.Contain("namespace A;"), "three members, so no file-scoped namespace");
        }
    }

    [Test]
    public void Render_LoneNamespace_IsFileScoped()
    {
        var sole = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "A", Members: [new TypeDeclaration(Name: "X")])],
            Header: Header);

        Assert.That(sole.Render(RenderOptions.Default), Does.Contain("namespace A;"));
    }

    [Test]
    public void Render_NamespaceInsideANamespace_KeepsBothAsBlocks()
    {
        var nested = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "A", Members: [new NamespaceDeclaration(Name: "B", Members: [new TypeDeclaration(Name: "X")])])],
            Header: Header);

        var text = nested.Render(RenderOptions.Default);

        Assert.That(text, Does.Contain("namespace A\n{\n    namespace B\n    {"), "a file cannot mix a file-scoped namespace with a block one");
        Compiling.AssertCompiles(text);
    }

    [Test]
    public void Render_NamespaceInsideAType_Throws()
    {
        var misplaced = new CompilationUnit(
            Members: [new TypeDeclaration(Name: "C", Members: [new NamespaceDeclaration(Name: "N")])],
            Header: Header);

        Assert.That(() => misplaced.Render(), Throws.TypeOf<RenderException>().With.Message.Contains("only appear in a file or a namespace"));
    }

    [Test]
    public void HintName_NamespacesAroundOneType_NamesTheFileAfterIt()
    {
        var sole = new CompilationUnit(Members: [new NamespaceDeclaration(Name: "A", Members: [new TypeDeclaration(Name: "X")])]);
        var crowded = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "A", Members: [new TypeDeclaration(Name: "X"), new TypeDeclaration(Name: "Y")])]);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(sole.HintName, Is.EqualTo("A.X.g.cs"));
            Assert.That(crowded.HintName, Is.EqualTo("Generated.g.cs"), "a namespace holding two types names no single file");
            Assert.That(new CompilationUnit().HintName, Is.EqualTo("Generated.g.cs"));
        }
    }

    [Test]
    public void Render_TypeWithContainingType_WritesPartialPartsAroundIt()
    {
        var outer = new TypeDeclaration(Name: "Outer", TypeParameters: [new TypeParameterDeclaration(Name: "T")]);
        var inner = new TypeDeclaration(
            Name: "Inner",
            Accessibility: Accessibility.Public,
            ContainingType: outer,
            Members: [new FieldDeclaration(Type: Types.Int32, Name: "x")]);
        var renamed = inner with { Name = "Renamed" };
        var unit = new CompilationUnit(Members: [new NamespaceDeclaration(Name: "N", Members: [inner])], Header: Header);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(unit.HintName, Is.EqualTo("N.Outer`1.Inner.g.cs"), "the name follows what it is declared in");
            Assert.That(renamed.ContainingType, Is.EqualTo(outer), "editing the type leaves what it is in alone");
            Assert.That(unit.Render(), Does.Contain("partial class Outer<T>\n{\n    public class Inner\n    {\n        int x;\n    }\n}"));
        }
    }

    [Test]
    public void Render_RefPropertyWithASetter_Throws()
    {
        var property = new PropertyDeclaration(
            Type: Types.Int32,
            Name: "P",
            RefKind: RefKind.Ref,
            Getter: new AccessorDeclaration(Body: Snippet.Expression("ref _x")),
            Setter: new AccessorDeclaration());
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [property])]);

        Assert.That(() => unit.Render(), Throws.TypeOf<RenderException>().With.Message.Contains("ref property"));
    }

    [Test]
    public void Render_EnumWithANonEnumMember_Throws()
    {
        var unit = new CompilationUnit(
            Members: [new TypeDeclaration(TypeKind: TypeKind.Enum, Name: "E", Members: [new FieldDeclaration(Type: Types.Int32, Name: "x")])],
            Header: Header);

        Assert.That(() => unit.Render(), Throws.TypeOf<RenderException>().With.Message.Contains("enum members"));
    }

    [Test]
    public void Render_MultiLineConstructorInitializer_IndentsItsLaterLines()
    {
        var constructor = new ConstructorDeclaration(Body: Snippet.Empty, Initializer: Snippet.From("base(\n    1)"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [constructor])]);

        Assert.That(unit.Render(), Does.Contain("    C() : base(\n        1)\n    {"));
    }

    [Test]
    public void Render_BlankLineInsideAnExpressionBody_StaysEmpty()
    {
        var method = new MethodDeclaration(ReturnType: Types.Int32, Name: "Get", Body: Snippet.Expression("a\n\n+ b"));
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [method])]);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(
                unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.Never }),
                Does.Contain("        return a\n\n        + b;"));
            Assert.That(
                unit.Render(RenderOptions.Default with { Methods = ExpressionBodyPreference.WhenPossible }),
                Does.Contain("    int Get() =>\n        a\n\n        + b;"));
        }
    }

    [Test]
    public void Render_ExplicitEventWithoutAccessors_Throws()
    {
        var @event = new EventDeclaration(Type: Types.EventHandler, Name: "Changed", ExplicitInterfaceSpecifier: Types.IDisposable);
        var unit = new CompilationUnit(Members: [new TypeDeclaration(Name: "C", Members: [@event])]);

        Assert.That(() => unit.Render(), Throws.InstanceOf<RenderException>());
    }
}
