using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using System.Linq;

namespace Redeclare.Tests;

/// <summary>
///     Reads a file that uses every declaration shape the reader knows, renders it back and compiles the result.
///     The shapes no other test renders live here: <c>this</c> and <c>scoped</c> parameters, base lists, static
///     constructors, explicit interface methods, attribute targets, <c>private protected</c>, <c>extern</c>,
///     <c>file</c>, and operators inside an extension block.
/// </summary>
[TestFixture]
public sealed class RoundTripTests
{
    private const string Source = """
        #nullable enable
        using System;
        using System.Runtime.InteropServices;

        namespace Trip
        {
            public interface IShape
            {
                int Sides { get; }
                void Draw();
                event EventHandler? Drawn;
            }

            public abstract class Base
            {
                protected Base(int seed) { }
                public abstract int Weight { get; }
                protected virtual void Touch() { }
            }

            public sealed class Shape : Base, IShape, IDisposable
            {
                private static readonly int _seed;
                private protected int _hidden;
                public required string Name { get; init; }

                static Shape() { _seed = 1; }
                public Shape() : base(_seed) { }

                public override int Weight => 1;
                int IShape.Sides => 3;
                void IShape.Draw() { }
                event EventHandler? IShape.Drawn { add { } remove { } }
                public int this[int index] { get => index; private set { } }

                [return: MaybeNullIfNone]
                public string? Find([Mark] in int key, scoped ref int cursor, params ReadOnlySpan<int> rest) => null;

                protected override void Touch() { }
                public void Dispose() { }

                [DllImport("kernel32")]
                public static extern void Beep();

                public unsafe static void Poke(int* target) { }
            }

            [AttributeUsage(AttributeTargets.ReturnValue)]
            public sealed class MaybeNullIfNoneAttribute : Attribute { }

            [AttributeUsage(AttributeTargets.Parameter)]
            public sealed class MarkAttribute : Attribute { }

            file sealed class Hidden { }

            public static class Extensions
            {
                public static int Twice(this int x) => x * 2;

                extension(Shape shape)
                {
                    public int Doubled => shape.Weight * 2;
                    public static Shape operator +(Shape a, Shape b) => a;
                    public void operator +=(int more) { }
                }
            }
        }
        """;

    private static readonly CSharpCompilation _compilation = Compiling.AssertCompiles(Source);

    [Test]
    public void Render_EveryShapeReadFromTheFixture_CompilesAgain()
    {
        // A file-local type has a mangled metadata name, so the namespace is walked instead of looked up.
        var members = _compilation.GlobalNamespace.GetNamespaceMembers().Single(n => n.Name == "Trip").GetTypeMembers()
            .Select(type => WithBodies(type.ToDeclaration()))
            .ToArray();
        var unit = new CompilationUnit(
            Members: [new NamespaceDeclaration(Name: "Trip", Members: [.. members])],
            Header: "// <auto-generated/>\n\n#nullable enable");

        var text = unit.Render();

        using (Assert.EnterMultipleScope())
        {
            Assert.That(text, Does.Contain("public sealed class Shape : global::Trip.Base, global::Trip.IShape, global::System.IDisposable"));
            Assert.That(text, Does.Contain("static Shape()"));
            Assert.That(text, Does.Contain("private protected int _hidden;"));
            Assert.That(text, Does.Contain("int global::Trip.IShape.Sides"));
            Assert.That(text, Does.Contain("void global::Trip.IShape.Draw()"));
            Assert.That(text, Does.Contain("[return: global::Trip.MaybeNullIfNoneAttribute]"));
            Assert.That(text, Does.Contain("Find([global::Trip.MarkAttribute] in int key, scoped ref int cursor, params global::System.ReadOnlySpan<int> rest)"));
            Assert.That(text, Does.Contain("public static extern void Beep();"));
            Assert.That(text, Does.Contain("public static unsafe void Poke(int* target)"));
            Assert.That(text, Does.Contain("file sealed class Hidden"));
            Assert.That(text, Does.Contain("public static int Twice(this int x)"));
            Assert.That(text, Does.Contain("public static global::Trip.Shape operator +(global::Trip.Shape a, global::Trip.Shape b)"));
            Assert.That(text, Does.Contain("public void operator +=(int more)"));
        }

        Compiling.AssertCompiles(text);
    }

    /// <summary>
    ///     Gives every member the reader left bodiless a body that compiles, so the file can be compiled whole.
    /// </summary>
    private static TypeDeclaration WithBodies(TypeDeclaration type)
    {
        return type with { Members = [.. type.Members.Select(WithBody)] };
    }

    /// <summary>
    ///     Gives a property's accessors bodies. A property in an extension block cannot be an auto-property.
    /// </summary>
    private static MemberDeclaration WithAccessorBodies(MemberDeclaration member)
    {
        return member is PropertyDeclaration property
            ? property with
            {
                Getter = property.Getter is { } get ? get with { Body = Snippet.From("throw null!;") } : null,
                Setter = property.Setter is { } set ? set with { Body = Snippet.Empty } : null,
            }
            : member;
    }

    private static MemberDeclaration WithBody(MemberDeclaration member)
    {
        const Modifiers bodiless = Modifiers.Abstract | Modifiers.Extern | Modifiers.Partial;

        return member switch
        {
            MethodDeclaration { Body: null } method when (method.Modifiers & bodiless) == 0
                => method with { Body = Snippet.From("throw null!;") },
            PropertyDeclaration { Parameters.IsEmpty: false } indexer
                => indexer with
                {
                    Getter = indexer.Getter is { } get ? get with { Body = Snippet.From("throw null!;") } : null,
                    Setter = indexer.Setter is { } set ? set with { Body = Snippet.Empty } : null,
                },
            EventDeclaration { ExplicitInterfaceSpecifier: not null } @event
                => @event with { Adder = new AccessorDeclaration(Body: Snippet.Empty), Remover = new AccessorDeclaration(Body: Snippet.Empty) },
            ConstructorDeclaration { Parameters.IsEmpty: true, Modifiers: Modifiers.None } constructor
                => constructor with { Initializer = Snippet.From("base(0)") },
            TypeDeclaration nested => WithBodies(nested),
            ExtensionDeclaration extension => extension with { Members = [.. extension.Members.Select(WithBody).Select(WithAccessorBodies)] },
            _ => member,
        };
    }
}
